### ISSUE TITLE
dimGrid, dimBlock undefined in matrix_cuda.cu

### ISSUE THREAD

**Issue by ajeetksingh** [lzcbetter/matrix-cuda#3]
Hi,

First of all thanks a lot for such a beautiful code. 
While compiling the code using `nvcc`, I am getting following error.

`matrix_cuda.cu(251): error: identifier "dimGrid" is undefined`

`matrix_cuda.cu(251): error: identifier "dimBlock" is undefined`

`matrix_cuda.cu(255): error: identifier "dimGrid" is undefined`

`matrix_cuda.cu(255): error: identifier "dimBlock" is undefined`

I tried un-commenting the relevant part in the code, but error still persists.
Can you point me to the right direction?
Thanks. :)

**Comment by lzhengchun** [comment]
do you compile with nvcc?

**Comment by saisharank** [comment]
Yes I am compiling with nvcc

**Comment by lzhengchun** [comment]
you can try to include cuda.h, but usually it is not needed with nvcc. I did not define those variables, they come from compiler / cuda runtime. If you still have problem, I would suggest you trying to make a hello work cuda program work first.

**Comment by sajal-vt** [comment]
So, I ran into the same problem. When I was searching for dimGrid, dimBlock variable declarations in matrix_cuda.cu, I found them missing (there is a block with commented out declaration). Can you please try to compile the code from here? My guess, something got lost in between your last successful compilation and last commit to the repo.

**Comment by lzhengchun** [comment]
Oh, sorry, it's my mistake while I merge a pull request. I did not review that PL carefully. I reverted that part of code. it should work now

**Comment by lzhengchun** [comment]
> So, I ran into the same problem. When I was searching for dimGrid, dimBlock variable declarations in matrix_cuda.cu, I found them missing (there is a block with commented out declaration). Can you please try to compile the code from here? My guess, something got lost in between your last successful compilation and last commit to the repo.

Oh, sorry, it's my mistake while I merge a pull request. I did not review that PL carefully. I reverted that part of code. it should work now
